(()=>{"use strict";
const NS="http://www.w3.org/2000/svg",data=window.DARK_RIVERS_DATA,config=window.DARK_RIVERS_CONFIG||{doi:"10.5281/zenodo.0000000",doiUrl:"https://zenodo.org/records/0000000"};
const $=id=>document.getElementById(id),els={network:$("riverNetwork"),flashes:$("flashLayer"),play:$("playButton"),reset:$("resetButton"),range:$("yearRange"),year:$("yearDisplay"),count:$("reachCount"),samples:$("sampleCount"),speed:$("speedSelect"),detail:$("reachDetail"),install:$("installApp"),dialog:$("installDialog"),instructions:$("installInstructions"),doi:$("doiPill"),doiText:$("doiText")};
const state={year:data.meta.minYear,playing:false,selected:null,last:0,carry:0,raf:null,prompt:null},paths=new Map(),reachById=new Map(data.reaches.map(r=>[r.id,r]));
const latestAt=year=>{const m=new Map();data.events.filter(e=>e.year<=year).forEach(e=>m.set(e.reachId,e));return m};
const latestFor=id=>data.events.filter(e=>e.reachId===id&&e.year<=state.year).at(-1)||null;
const ageBand=year=>{const age=state.year-year;if(age<=1)return"fresh";if(age<=5)return"recent";if(age<=15)return"aged";return"old"};
function addReach(r){const p=document.createElementNS(NS,"path");p.setAttribute("d",r.d);p.setAttribute("class","river-reach");p.setAttribute("tabindex","0");p.setAttribute("role","button");p.dataset.id=r.id;p.addEventListener("click",()=>select(r.id));p.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();select(r.id)}});els.network.appendChild(p);paths.set(r.id,p)}
function render(flash=false){const latest=latestAt(state.year);for(const r of data.reaches){const p=paths.get(r.id),obs=latest.get(r.id);p.classList.toggle("is-selected",state.selected===r.id);if(obs){p.dataset.status=obs.status;p.dataset.age=ageBand(obs.year);p.setAttribute("aria-label",`${r.name}, ${obs.status}, ${obs.q}, observed ${obs.year}`)}else{delete p.dataset.status;delete p.dataset.age;p.setAttribute("aria-label",`${r.name}, no revealed observation`)}}els.year.textContent=state.year;els.range.value=state.year;els.count.textContent=`${latest.size} / ${data.reaches.length}`;els.samples.textContent=data.events.filter(e=>e.year<=state.year).length;if(flash)data.events.filter(e=>e.year===state.year).forEach(showFlash);renderDetail()}
function showFlash(e){const p=paths.get(e.reachId);if(!p||typeof p.getPointAtLength!=="function")return;p.classList.add("is-just-observed");setTimeout(()=>p.classList.remove("is-just-observed"),850);const pt=p.getPointAtLength(p.getTotalLength()/2),c=document.createElementNS(NS,"circle");c.setAttribute("cx",pt.x);c.setAttribute("cy",pt.y);c.setAttribute("r","3");c.setAttribute("class","sample-flash");els.flashes.appendChild(c);if(c.animate&&!matchMedia("(prefers-reduced-motion: reduce)").matches){const a=c.animate([{opacity:0,r:2},{opacity:.92,r:5,offset:.22},{opacity:.55,r:9,offset:.58},{opacity:0,r:13}],{duration:720,easing:"ease-out"});a.onfinish=()=>c.remove()}else setTimeout(()=>c.remove(),350)}
function select(id){state.selected=id;render()}
function renderDetail(){if(!state.selected)return;const r=reachById.get(state.selected),e=latestFor(state.selected);els.detail.innerHTML=e?`<p class="detail-kicker">${r.name}</p><h2>${e.status} · ${e.q}</h2><p>Latest observation revealed by the selected year. The dimming reflects age of observation, not a change in ecological condition.</p><div class="detail-grid"><div><span>Observation</span><strong>${e.year}</strong></div><div><span>Sampling point</span><strong>${e.station}</strong></div></div>`:`<p class="detail-kicker">${r.name}</p><h2>Still dark in ${state.year}</h2><p>No prototype sample has been revealed for this reach by the selected year.</p>`}
function setYear(y,flash=false){state.year=Math.max(data.meta.minYear,Math.min(data.meta.maxYear,+y));render(flash)}
function setPlaying(on){state.playing=on;els.play.setAttribute("aria-pressed",String(on));els.play.textContent=on?"❚❚ Pause":"▶ Play";if(!on&&state.raf){cancelAnimationFrame(state.raf);state.raf=null}if(on){if(state.year>=data.meta.maxYear)setYear(data.meta.minYear);state.last=performance.now();state.carry=0;state.raf=requestAnimationFrame(tick)}}
function tick(now){if(!state.playing)return;state.carry+=Math.min((now-state.last)/1000,.5)*Number(els.speed.value||3);state.last=now;while(state.carry>=1&&state.playing){state.carry-=1;if(state.year>=data.meta.maxYear){setPlaying(false);break}setYear(state.year+1,true)}if(state.playing)state.raf=requestAnimationFrame(tick)}
function reset(){setPlaying(false);state.selected=null;els.flashes.replaceChildren();setYear(data.meta.minYear);els.detail.innerHTML='<p class="detail-kicker">Select a reach</p><h2>What do we know here?</h2><p>Click or tap a river reach to inspect its latest revealed observation. Darkness means the timeline has not yet revealed an observation there.</p>'}
function setupInstall(){if(matchMedia("(display-mode: standalone)").matches||navigator.standalone===true)els.install.hidden=true;addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.prompt=e;els.install.hidden=false;els.install.classList.add("is-ready")});addEventListener("appinstalled",()=>els.install.hidden=true);els.install.addEventListener("click",async()=>{if(state.prompt){const p=state.prompt;state.prompt=null;p.prompt();await p.userChoice;return}const ua=navigator.userAgent||"",apple=/iphone|ipad|ipod/i.test(ua),android=/android/i.test(ua);els.instructions.innerHTML=apple?'<p>In Safari, tap <strong>Share</strong>, then choose <strong>Add to Home Screen</strong>.</p>':android?'<p>Open the browser menu and choose <strong>Install app</strong> or <strong>Add to Home screen</strong>.</p>':'<p>Use the install icon in the address bar, or the browser menu’s <strong>Install app</strong> command.</p>';if(els.dialog.showModal)els.dialog.showModal()})}
function setupPwa(){if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./service-worker.js",{scope:"./"}).catch(e=>console.warn("Dark Rivers service worker registration failed:",e))}
function init(){data.reaches.forEach(addReach);els.play.addEventListener("click",()=>setPlaying(!state.playing));els.reset.addEventListener("click",reset);els.range.addEventListener("input",e=>{setPlaying(false);setYear(e.target.value)});els.doiText.textContent=config.doi;els.doi.href=config.doiUrl;els.doi.classList.toggle("is-placeholder",config.doi.includes("0000000"));setupInstall();setupPwa();render(true)}
init();
})();
