const FAST_PROGRAMME = Object.freeze({
  x: 1080,
  y: 1523,
  z: 1949
});

const sliderIds = ['speedX', 'speedY', 'speedZ'];
const axisIds = ['axisX', 'axisY', 'axisZ'];

function dispatch(element, type) {
  element?.dispatchEvent(new Event(type, { bubbles: true }));
}

function setChecked(element, checked) {
  if (!element || element.checked === checked) return;
  element.checked = checked;
  dispatch(element, 'change');
}

function setRange(element, value) {
  if (!element) return;
  element.value = String(value);
  dispatch(element, 'input');
}

function applyFastProgramme() {
  const axes = axisIds.map(id => document.getElementById(id));
  const speeds = sliderIds.map(id => document.getElementById(id));
  if (axes.some(item => !item) || speeds.some(item => !item)) return;

  axes.forEach(axis => setChecked(axis, true));
  setRange(speeds[0], FAST_PROGRAMME.x);
  setRange(speeds[1], FAST_PROGRAMME.y);
  setRange(speeds[2], FAST_PROGRAMME.z);

  const traceRate = document.getElementById('traceRate');
  setRange(traceRate, 5);

  const showTrail = document.getElementById('showTrail');
  setChecked(showTrail, true);

  // Hide the guide sphere during the fast experiment. The visible sphere should
  // be generated by the accumulated rotational envelope, not by the reference mesh.
  const showSphere = document.getElementById('showSphere');
  setChecked(showSphere, false);

  const interpretation = document.getElementById('interpretation');
  if (interpretation) {
    interpretation.textContent = 'SPHERISE is sampling rapidly mismatched X/Y/Z phases. At this speed, sequential orientations accumulate fast enough to approximate the paper\'s “all perspectives at once” view. The bright sphere is the trace itself; the guide sphere is hidden.';
  }
}

window.addEventListener('load', () => {
  for (const id of sliderIds) {
    const slider = document.getElementById(id);
    if (slider) {
      slider.min = '-2160';
      slider.max = '2160';
      slider.step = '1';
    }
  }

  const fastButton = document.querySelector('[data-preset="xyz"]');
  if (fastButton) {
    fastButton.textContent = 'SPHERISE · fast';
    fastButton.setAttribute('title', 'Approximate all perspectives rapidly');
    fastButton.addEventListener('click', () => {
      // app.js handles the base preset first; this listener then raises it into
      // the high-speed perception experiment.
      applyFastProgramme();
    });
  }

  const reduceMotion = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
  if (!reduceMotion && fastButton?.classList.contains('active')) {
    applyFastProgramme();
  }
});
